version: "2.3"
services:

  zookeeper:
    volumes:
      - $PWD/jmx-monitoring-stacks/jmxexporter-prometheus-grafana/assets/prometheus/jmx-exporter/:/usr/share/jmx-exporter
    environment:
      EXTRA_ARGS: -javaagent:/usr/share/jmx-exporter/jmx_prometheus_javaagent-0.12.0.jar=1234:/usr/share/jmx-exporter/zookeeper.yml

  kafka1:
    volumes:
      - $PWD/jmx-monitoring-stacks/jmxexporter-prometheus-grafana/assets/prometheus/jmx-exporter/:/usr/share/jmx-exporter
    environment:
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/secrets/broker_jaas.conf
                  -Djavax.net.ssl.trustStore=/etc/kafka/secrets/kafka.kafka1.truststore.jks
                  -Djavax.net.ssl.trustStorePassword=confluent
                  -javaagent:/usr/share/jmx-exporter/jmx_prometheus_javaagent-0.12.0.jar=1234:/usr/share/jmx-exporter/kafka-broker.yml

  kafka2:
    volumes:
      - $PWD/jmx-monitoring-stacks/jmxexporter-prometheus-grafana/assets/prometheus/jmx-exporter/:/usr/share/jmx-exporter
    environment:
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/secrets/broker_jaas.conf
                  -Djavax.net.ssl.trustStore=/etc/kafka/secrets/kafka.kafka2.truststore.jks
                  -Djavax.net.ssl.trustStorePassword=confluent
                  -javaagent:/usr/share/jmx-exporter/jmx_prometheus_javaagent-0.12.0.jar=1234:/usr/share/jmx-exporter/kafka-broker.yml

  connect:
    volumes:
      - $PWD/jmx-monitoring-stacks/jmxexporter-prometheus-grafana/assets/prometheus/jmx-exporter/:/tmp/jmx-exporter

  prometheus:
    image: prom/prometheus:v2.11.1
    ports:
      - 9090:9090
    volumes:
      - $PWD/jmx-monitoring-stacks/jmxexporter-prometheus-grafana/assets/prometheus/prometheus-config/:/etc/prometheus/

  node-exporter:
    image: prom/node-exporter:v0.18.1
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points'
      - '^(aufs|proc|nsfs|shm|cgroup|tmpfs|binfmt_misc|debugfs|devpts|fusectl|hugetlbfs|fuse.lxcfs|mqueue|pstore|securityfs|sysfs|autofs|devtmpfs|configfs)'

  kafka-lag-exporter:
    image: lightbend/kafka-lag-exporter:0.5.5
    hostname: kafka-lag-exporter
    restart: always
    volumes:
      - $PWD/jmx-monitoring-stacks/jmxexporter-prometheus-grafana/assets/prometheus/kafka-lag-exporter:/opt/docker/conf
      - ./scripts/security:/etc/kafka/secrets

  grafana:
    image: grafana/grafana:6.6.2
    environment:
      GF_INSTALL_PLUGINS: grafana-piechart-panel
    ports:
      - 3000:3000
    volumes:
      - $PWD/jmx-monitoring-stacks/jmxexporter-prometheus-grafana/assets//prometheus/grafana/provisioning/:/etc/grafana/provisioning/
